```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)
library(ggpubr)
library(data.table)
library(JWileymisc)
library(lme4)
library(lmerTest)
library(drc)


data <- read.table("/Users/tand0009/WorkGit/projects/inprogress/Edison_scripts/TF/../Edison_Tables/Edison_Table_Pow_vFigure.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)


data$PowSlopeBin[data$PowSlopeBin=='NaN']<-NA
data$PowBGBin[data$PowBGBin=='NaN']<-NA
data$PowDeltaBin[data$PowDeltaBin=='NaN']<-NA
data$PowThetaBin[data$PowThetaBin=='NaN']<-NA
data$PowAlphaBin[data$PowAlphaBin=='NaN']<-NA

data<-data[is.na(data$PowDelta)==FALSE & is.na(data$PowSlopeBin)==FALSE & data$SleepGroup!="<undefined>",]

data$SleepGroup<-as.factor(data$SleepGroup)


data$PowSlopeBin<-as.factor(data$PowSlopeBin)
data$PowBGBin<-as.factor(data$PowBGBin)
data$PowDeltaBin<-as.factor(data$PowDeltaBin)
data$PowThetaBin<-as.factor(data$PowThetaBin)
data$PowAlphaBin<-as.factor(data$PowAlphaBin)

data$PowSlopeBin<-relevel(data$PowSlopeBin,"1")
data$PowBGBin<-relevel(data$PowBGBin,"1")
data$PowDeltaBin<-relevel(data$PowDeltaBin,"1")
data$PowThetaBin<-relevel(data$PowThetaBin,"1")
data$PowAlphaBin<-relevel(data$PowAlphaBin,"2")


#data$SleepGroup<-relevel(data$SleepGroup,"1")


data$zPowDelta<-(data$PowDelta-mean(data$PowDelta,na.rm=TRUE))/sd(data$PowDelta,na.rm=TRUE)
data$zPowDeltaSq<-(data$zPowDelta)^2
data$zPowTheta<-(data$PowTheta-mean(data$PowTheta,na.rm=TRUE))/sd(data$PowTheta,na.rm=TRUE)
data$zPowThetaSq<-(data$zPowTheta)^2
data$zPowAlpha<-(data$PowAlpha-mean(data$PowAlpha,na.rm=TRUE))/sd(data$PowAlpha,na.rm=TRUE)
data$zPowAlphaSq<-(data$zPowAlpha)^2

lm0 <- glm(InsightPost ~ 1, family="binomial", data = data)
lm1 <- glm(InsightPost ~ 1 + SleepEdison, family="binomial", data = data)
lm1b <- glm(InsightPost ~ 1 + PowDelta, family="binomial", data = data)
lm2 <- glm(InsightPost ~ 1 + SleepEdison + PowDelta, family="binomial", data = data)
lm3 <- glm(InsightPost ~ 1 + SleepEdison + PowDelta, family="binomial", data = data)

lm0 <- glm(InsightPost ~ 1 , family="binomial", data = data)
lm1b <- glm(InsightPost ~ 1 + zPowDelta , family="binomial", data = data)
lm2b <- glm(InsightPost ~ 1 + zPowTheta, family="binomial", data = data)
lm3b <- glm(InsightPost ~ 1 + zPowAlpha , family="binomial", data = data)
lm1c <- glm(InsightPost ~ 1 + zPowDeltaSq , family="binomial", data = data)
lm2c <- glm(InsightPost ~ 1 + zPowThetaSq, family="binomial", data = data)
lm3c <- glm(InsightPost ~ 1 + zPowAlphaSq , family="binomial", data = data)


```

```